version: "3.9"

services:
  db:
    container_name: canc-store-db
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=pass12!@
      - POSTGRES_USER=canc_user
      - POSTGRES_DB=canc_db
    networks:
      - canc-store-net
    volumes:
      - canc-store-db:/var/lib/postgres/data
    ports:
      - "5432:5432"
    restart: always
  
  app:
    container_name: canc-store-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:80"
    networks:
      - canc-store-net
    restart: always

volumes:
  canc-store-db:
    driver: local

networks:
  canc-store-net:
    driver: bridge